### ISSUE TITLE
https certificate for https://www.pyqtgraph.org

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph.github.io#1]
Trying to pull this up right now, results in an invalid certificate:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/646398/120081758-09e9f900-c074-11eb-8436-b1484a7010ec.png">

Not sure what the process is to fix this (as how the web works is a huge black hole to me).

**Comment by ixjlyons** [comment]
Looks like this can be closed

![Screenshot_2021-06-06_15-05-37](https://user-images.githubusercontent.com/943602/120941670-b3666580-c6d8-11eb-9f2d-05dd46b95c8a.png)

**Comment by j9ac9k** [comment]
Blerg, yeah, ... given I commented on another issue that was related, definitely should have caught this.  Thanks @ixjlyons
